version: '3.9'

services:
  products:
    build:
      context: ./products
    container_name: products_service
    ports:
      - "8001:8001"
    env_file:
      - ./products/.env
    volumes:
      - ./products/app:/app/app  # solo el código
    command: ["sh", "./entrypoint.sh"]
    networks:
      - backend_net

  inventory:
    build:
      context: ./inventory
    container_name: inventory_service
    ports:
      - "8002:8002"
    env_file:
      - ./inventory/.env
    volumes:
      - ./inventory/app:/app/app  # solo el código
    depends_on:
      - products
    command: ["sh", "./entrypoint.sh"]
    networks:
      - backend_net

networks:
  backend_net:
    driver: bridge
